// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.hubspot.hbase.filter.example;

public final class ExampleProtos {
  private ExampleProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChildProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 child_proto_val = 1;
    boolean hasChildProtoVal();
    int getChildProtoVal();
  }
  public static final class ChildProto extends
      com.google.protobuf.GeneratedMessage
      implements ChildProtoOrBuilder {
    // Use ChildProto.newBuilder() to construct.
    private ChildProto(Builder builder) {
      super(builder);
    }
    private ChildProto(boolean noInit) {}
    
    private static final ChildProto defaultInstance;
    public static ChildProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChildProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hubspot.hbase.filter.example.ExampleProtos.internal_static_com_hubspot_hbase_filter_example_ChildProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hubspot.hbase.filter.example.ExampleProtos.internal_static_com_hubspot_hbase_filter_example_ChildProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 child_proto_val = 1;
    public static final int CHILD_PROTO_VAL_FIELD_NUMBER = 1;
    private int childProtoVal_;
    public boolean hasChildProtoVal() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getChildProtoVal() {
      return childProtoVal_;
    }
    
    private void initFields() {
      childProtoVal_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, childProtoVal_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, childProtoVal_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hubspot.hbase.filter.example.ExampleProtos.ChildProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ChildProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ChildProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ChildProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ChildProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ChildProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ChildProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ChildProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ChildProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ChildProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hubspot.hbase.filter.example.ExampleProtos.ChildProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hubspot.hbase.filter.example.ExampleProtos.ChildProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hubspot.hbase.filter.example.ExampleProtos.internal_static_com_hubspot_hbase_filter_example_ChildProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hubspot.hbase.filter.example.ExampleProtos.internal_static_com_hubspot_hbase_filter_example_ChildProto_fieldAccessorTable;
      }
      
      // Construct using com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        childProtoVal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.getDescriptor();
      }
      
      public com.hubspot.hbase.filter.example.ExampleProtos.ChildProto getDefaultInstanceForType() {
        return com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.getDefaultInstance();
      }
      
      public com.hubspot.hbase.filter.example.ExampleProtos.ChildProto build() {
        com.hubspot.hbase.filter.example.ExampleProtos.ChildProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hubspot.hbase.filter.example.ExampleProtos.ChildProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hubspot.hbase.filter.example.ExampleProtos.ChildProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hubspot.hbase.filter.example.ExampleProtos.ChildProto buildPartial() {
        com.hubspot.hbase.filter.example.ExampleProtos.ChildProto result = new com.hubspot.hbase.filter.example.ExampleProtos.ChildProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.childProtoVal_ = childProtoVal_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hubspot.hbase.filter.example.ExampleProtos.ChildProto) {
          return mergeFrom((com.hubspot.hbase.filter.example.ExampleProtos.ChildProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hubspot.hbase.filter.example.ExampleProtos.ChildProto other) {
        if (other == com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.getDefaultInstance()) return this;
        if (other.hasChildProtoVal()) {
          setChildProtoVal(other.getChildProtoVal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              childProtoVal_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 child_proto_val = 1;
      private int childProtoVal_ ;
      public boolean hasChildProtoVal() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getChildProtoVal() {
        return childProtoVal_;
      }
      public Builder setChildProtoVal(int value) {
        bitField0_ |= 0x00000001;
        childProtoVal_ = value;
        onChanged();
        return this;
      }
      public Builder clearChildProtoVal() {
        bitField0_ = (bitField0_ & ~0x00000001);
        childProtoVal_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.hubspot.hbase.filter.example.ChildProto)
    }
    
    static {
      defaultInstance = new ChildProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.hubspot.hbase.filter.example.ChildProto)
  }
  
  public interface ExampleProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 id = 1;
    boolean hasId();
    long getId();
    
    // optional int32 portal_id = 2;
    boolean hasPortalId();
    int getPortalId();
    
    // optional string name = 3;
    boolean hasName();
    String getName();
    
    // optional bool bool_test = 4;
    boolean hasBoolTest();
    boolean getBoolTest();
    
    // optional float float_test = 5;
    boolean hasFloatTest();
    float getFloatTest();
    
    // optional bytes bytes_test = 6;
    boolean hasBytesTest();
    com.google.protobuf.ByteString getBytesTest();
    
    // required int32 required_test = 7;
    boolean hasRequiredTest();
    int getRequiredTest();
    
    // repeated string array_values = 8;
    java.util.List<String> getArrayValuesList();
    int getArrayValuesCount();
    String getArrayValues(int index);
    
    // optional .com.hubspot.hbase.filter.example.ChildProto child_proto = 9;
    boolean hasChildProto();
    com.hubspot.hbase.filter.example.ExampleProtos.ChildProto getChildProto();
    com.hubspot.hbase.filter.example.ExampleProtos.ChildProtoOrBuilder getChildProtoOrBuilder();
    
    // optional .com.hubspot.hbase.filter.example.ExampleProto.TestEnum test_enum = 10;
    boolean hasTestEnum();
    com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.TestEnum getTestEnum();
    
    // optional double double_test = 11;
    boolean hasDoubleTest();
    double getDoubleTest();
    
    // optional int32 default_test = 12 [default = 5];
    boolean hasDefaultTest();
    int getDefaultTest();
  }
  public static final class ExampleProto extends
      com.google.protobuf.GeneratedMessage
      implements ExampleProtoOrBuilder {
    // Use ExampleProto.newBuilder() to construct.
    private ExampleProto(Builder builder) {
      super(builder);
    }
    private ExampleProto(boolean noInit) {}
    
    private static final ExampleProto defaultInstance;
    public static ExampleProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public ExampleProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hubspot.hbase.filter.example.ExampleProtos.internal_static_com_hubspot_hbase_filter_example_ExampleProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hubspot.hbase.filter.example.ExampleProtos.internal_static_com_hubspot_hbase_filter_example_ExampleProto_fieldAccessorTable;
    }
    
    public enum TestEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      APPLE(0, 1),
      ORANGE(1, 2),
      ;
      
      public static final int APPLE_VALUE = 1;
      public static final int ORANGE_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static TestEnum valueOf(int value) {
        switch (value) {
          case 1: return APPLE;
          case 2: return ORANGE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<TestEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<TestEnum>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TestEnum>() {
              public TestEnum findValueByNumber(int number) {
                return TestEnum.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final TestEnum[] VALUES = {
        APPLE, ORANGE, 
      };
      
      public static TestEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private TestEnum(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.hubspot.hbase.filter.example.ExampleProto.TestEnum)
    }
    
    public interface InnerProtoOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // optional string name = 1;
      boolean hasName();
      String getName();
    }
    public static final class InnerProto extends
        com.google.protobuf.GeneratedMessage
        implements InnerProtoOrBuilder {
      // Use InnerProto.newBuilder() to construct.
      private InnerProto(Builder builder) {
        super(builder);
      }
      private InnerProto(boolean noInit) {}
      
      private static final InnerProto defaultInstance;
      public static InnerProto getDefaultInstance() {
        return defaultInstance;
      }
      
      public InnerProto getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hubspot.hbase.filter.example.ExampleProtos.internal_static_com_hubspot_hbase_filter_example_ExampleProto_InnerProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hubspot.hbase.filter.example.ExampleProtos.internal_static_com_hubspot_hbase_filter_example_ExampleProto_InnerProto_fieldAccessorTable;
      }
      
      private int bitField0_;
      // optional string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            name_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        name_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProtoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.hubspot.hbase.filter.example.ExampleProtos.internal_static_com_hubspot_hbase_filter_example_ExampleProto_InnerProto_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.hubspot.hbase.filter.example.ExampleProtos.internal_static_com_hubspot_hbase_filter_example_ExampleProto_InnerProto_fieldAccessorTable;
        }
        
        // Construct using com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto.getDescriptor();
        }
        
        public com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto getDefaultInstanceForType() {
          return com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto.getDefaultInstance();
        }
        
        public com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto build() {
          com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto buildPartial() {
          com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto result = new com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto) {
            return mergeFrom((com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto other) {
          if (other == com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto.getDefaultInstance()) return this;
          if (other.hasName()) {
            setName(other.getName());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional string name = 1;
        private java.lang.Object name_ = "";
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        void setName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:com.hubspot.hbase.filter.example.ExampleProto.InnerProto)
      }
      
      static {
        defaultInstance = new InnerProto(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:com.hubspot.hbase.filter.example.ExampleProto.InnerProto)
    }
    
    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional int32 portal_id = 2;
    public static final int PORTAL_ID_FIELD_NUMBER = 2;
    private int portalId_;
    public boolean hasPortalId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getPortalId() {
      return portalId_;
    }
    
    // optional string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool bool_test = 4;
    public static final int BOOL_TEST_FIELD_NUMBER = 4;
    private boolean boolTest_;
    public boolean hasBoolTest() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getBoolTest() {
      return boolTest_;
    }
    
    // optional float float_test = 5;
    public static final int FLOAT_TEST_FIELD_NUMBER = 5;
    private float floatTest_;
    public boolean hasFloatTest() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public float getFloatTest() {
      return floatTest_;
    }
    
    // optional bytes bytes_test = 6;
    public static final int BYTES_TEST_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString bytesTest_;
    public boolean hasBytesTest() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.google.protobuf.ByteString getBytesTest() {
      return bytesTest_;
    }
    
    // required int32 required_test = 7;
    public static final int REQUIRED_TEST_FIELD_NUMBER = 7;
    private int requiredTest_;
    public boolean hasRequiredTest() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getRequiredTest() {
      return requiredTest_;
    }
    
    // repeated string array_values = 8;
    public static final int ARRAY_VALUES_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList arrayValues_;
    public java.util.List<String>
        getArrayValuesList() {
      return arrayValues_;
    }
    public int getArrayValuesCount() {
      return arrayValues_.size();
    }
    public String getArrayValues(int index) {
      return arrayValues_.get(index);
    }
    
    // optional .com.hubspot.hbase.filter.example.ChildProto child_proto = 9;
    public static final int CHILD_PROTO_FIELD_NUMBER = 9;
    private com.hubspot.hbase.filter.example.ExampleProtos.ChildProto childProto_;
    public boolean hasChildProto() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.hubspot.hbase.filter.example.ExampleProtos.ChildProto getChildProto() {
      return childProto_;
    }
    public com.hubspot.hbase.filter.example.ExampleProtos.ChildProtoOrBuilder getChildProtoOrBuilder() {
      return childProto_;
    }
    
    // optional .com.hubspot.hbase.filter.example.ExampleProto.TestEnum test_enum = 10;
    public static final int TEST_ENUM_FIELD_NUMBER = 10;
    private com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.TestEnum testEnum_;
    public boolean hasTestEnum() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.TestEnum getTestEnum() {
      return testEnum_;
    }
    
    // optional double double_test = 11;
    public static final int DOUBLE_TEST_FIELD_NUMBER = 11;
    private double doubleTest_;
    public boolean hasDoubleTest() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public double getDoubleTest() {
      return doubleTest_;
    }
    
    // optional int32 default_test = 12 [default = 5];
    public static final int DEFAULT_TEST_FIELD_NUMBER = 12;
    private int defaultTest_;
    public boolean hasDefaultTest() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public int getDefaultTest() {
      return defaultTest_;
    }
    
    private void initFields() {
      id_ = 0L;
      portalId_ = 0;
      name_ = "";
      boolTest_ = false;
      floatTest_ = 0F;
      bytesTest_ = com.google.protobuf.ByteString.EMPTY;
      requiredTest_ = 0;
      arrayValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      childProto_ = com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.getDefaultInstance();
      testEnum_ = com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.TestEnum.APPLE;
      doubleTest_ = 0D;
      defaultTest_ = 5;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRequiredTest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, portalId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, boolTest_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, floatTest_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, bytesTest_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, requiredTest_);
      }
      for (int i = 0; i < arrayValues_.size(); i++) {
        output.writeBytes(8, arrayValues_.getByteString(i));
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(9, childProto_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeEnum(10, testEnum_.getNumber());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeDouble(11, doubleTest_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(12, defaultTest_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, portalId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, boolTest_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, floatTest_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, bytesTest_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, requiredTest_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < arrayValues_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(arrayValues_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getArrayValuesList().size();
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, childProto_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, testEnum_.getNumber());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, doubleTest_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, defaultTest_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hubspot.hbase.filter.example.ExampleProtos.ExampleProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hubspot.hbase.filter.example.ExampleProtos.internal_static_com_hubspot_hbase_filter_example_ExampleProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hubspot.hbase.filter.example.ExampleProtos.internal_static_com_hubspot_hbase_filter_example_ExampleProto_fieldAccessorTable;
      }
      
      // Construct using com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getChildProtoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        portalId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        boolTest_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        floatTest_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        bytesTest_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        requiredTest_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        arrayValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        if (childProtoBuilder_ == null) {
          childProto_ = com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.getDefaultInstance();
        } else {
          childProtoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        testEnum_ = com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.TestEnum.APPLE;
        bitField0_ = (bitField0_ & ~0x00000200);
        doubleTest_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000400);
        defaultTest_ = 5;
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.getDescriptor();
      }
      
      public com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto getDefaultInstanceForType() {
        return com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.getDefaultInstance();
      }
      
      public com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto build() {
        com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto buildPartial() {
        com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto result = new com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.portalId_ = portalId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.boolTest_ = boolTest_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.floatTest_ = floatTest_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.bytesTest_ = bytesTest_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.requiredTest_ = requiredTest_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          arrayValues_ = new com.google.protobuf.UnmodifiableLazyStringList(
              arrayValues_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.arrayValues_ = arrayValues_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        if (childProtoBuilder_ == null) {
          result.childProto_ = childProto_;
        } else {
          result.childProto_ = childProtoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.testEnum_ = testEnum_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.doubleTest_ = doubleTest_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000400;
        }
        result.defaultTest_ = defaultTest_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto) {
          return mergeFrom((com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto other) {
        if (other == com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPortalId()) {
          setPortalId(other.getPortalId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasBoolTest()) {
          setBoolTest(other.getBoolTest());
        }
        if (other.hasFloatTest()) {
          setFloatTest(other.getFloatTest());
        }
        if (other.hasBytesTest()) {
          setBytesTest(other.getBytesTest());
        }
        if (other.hasRequiredTest()) {
          setRequiredTest(other.getRequiredTest());
        }
        if (!other.arrayValues_.isEmpty()) {
          if (arrayValues_.isEmpty()) {
            arrayValues_ = other.arrayValues_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureArrayValuesIsMutable();
            arrayValues_.addAll(other.arrayValues_);
          }
          onChanged();
        }
        if (other.hasChildProto()) {
          mergeChildProto(other.getChildProto());
        }
        if (other.hasTestEnum()) {
          setTestEnum(other.getTestEnum());
        }
        if (other.hasDoubleTest()) {
          setDoubleTest(other.getDoubleTest());
        }
        if (other.hasDefaultTest()) {
          setDefaultTest(other.getDefaultTest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRequiredTest()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              portalId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              boolTest_ = input.readBool();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              floatTest_ = input.readFloat();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              bytesTest_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              requiredTest_ = input.readInt32();
              break;
            }
            case 66: {
              ensureArrayValuesIsMutable();
              arrayValues_.add(input.readBytes());
              break;
            }
            case 74: {
              com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.Builder subBuilder = com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.newBuilder();
              if (hasChildProto()) {
                subBuilder.mergeFrom(getChildProto());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChildProto(subBuilder.buildPartial());
              break;
            }
            case 80: {
              int rawValue = input.readEnum();
              com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.TestEnum value = com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.TestEnum.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(10, rawValue);
              } else {
                bitField0_ |= 0x00000200;
                testEnum_ = value;
              }
              break;
            }
            case 89: {
              bitField0_ |= 0x00000400;
              doubleTest_ = input.readDouble();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              defaultTest_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int32 portal_id = 2;
      private int portalId_ ;
      public boolean hasPortalId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getPortalId() {
        return portalId_;
      }
      public Builder setPortalId(int value) {
        bitField0_ |= 0x00000002;
        portalId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPortalId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        portalId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string name = 3;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
      }
      
      // optional bool bool_test = 4;
      private boolean boolTest_ ;
      public boolean hasBoolTest() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getBoolTest() {
        return boolTest_;
      }
      public Builder setBoolTest(boolean value) {
        bitField0_ |= 0x00000008;
        boolTest_ = value;
        onChanged();
        return this;
      }
      public Builder clearBoolTest() {
        bitField0_ = (bitField0_ & ~0x00000008);
        boolTest_ = false;
        onChanged();
        return this;
      }
      
      // optional float float_test = 5;
      private float floatTest_ ;
      public boolean hasFloatTest() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public float getFloatTest() {
        return floatTest_;
      }
      public Builder setFloatTest(float value) {
        bitField0_ |= 0x00000010;
        floatTest_ = value;
        onChanged();
        return this;
      }
      public Builder clearFloatTest() {
        bitField0_ = (bitField0_ & ~0x00000010);
        floatTest_ = 0F;
        onChanged();
        return this;
      }
      
      // optional bytes bytes_test = 6;
      private com.google.protobuf.ByteString bytesTest_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasBytesTest() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.google.protobuf.ByteString getBytesTest() {
        return bytesTest_;
      }
      public Builder setBytesTest(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        bytesTest_ = value;
        onChanged();
        return this;
      }
      public Builder clearBytesTest() {
        bitField0_ = (bitField0_ & ~0x00000020);
        bytesTest_ = getDefaultInstance().getBytesTest();
        onChanged();
        return this;
      }
      
      // required int32 required_test = 7;
      private int requiredTest_ ;
      public boolean hasRequiredTest() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getRequiredTest() {
        return requiredTest_;
      }
      public Builder setRequiredTest(int value) {
        bitField0_ |= 0x00000040;
        requiredTest_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequiredTest() {
        bitField0_ = (bitField0_ & ~0x00000040);
        requiredTest_ = 0;
        onChanged();
        return this;
      }
      
      // repeated string array_values = 8;
      private com.google.protobuf.LazyStringList arrayValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureArrayValuesIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          arrayValues_ = new com.google.protobuf.LazyStringArrayList(arrayValues_);
          bitField0_ |= 0x00000080;
         }
      }
      public java.util.List<String>
          getArrayValuesList() {
        return java.util.Collections.unmodifiableList(arrayValues_);
      }
      public int getArrayValuesCount() {
        return arrayValues_.size();
      }
      public String getArrayValues(int index) {
        return arrayValues_.get(index);
      }
      public Builder setArrayValues(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArrayValuesIsMutable();
        arrayValues_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addArrayValues(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArrayValuesIsMutable();
        arrayValues_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllArrayValues(
          java.lang.Iterable<String> values) {
        ensureArrayValuesIsMutable();
        super.addAll(values, arrayValues_);
        onChanged();
        return this;
      }
      public Builder clearArrayValues() {
        arrayValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      void addArrayValues(com.google.protobuf.ByteString value) {
        ensureArrayValuesIsMutable();
        arrayValues_.add(value);
        onChanged();
      }
      
      // optional .com.hubspot.hbase.filter.example.ChildProto child_proto = 9;
      private com.hubspot.hbase.filter.example.ExampleProtos.ChildProto childProto_ = com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.hubspot.hbase.filter.example.ExampleProtos.ChildProto, com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.Builder, com.hubspot.hbase.filter.example.ExampleProtos.ChildProtoOrBuilder> childProtoBuilder_;
      public boolean hasChildProto() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public com.hubspot.hbase.filter.example.ExampleProtos.ChildProto getChildProto() {
        if (childProtoBuilder_ == null) {
          return childProto_;
        } else {
          return childProtoBuilder_.getMessage();
        }
      }
      public Builder setChildProto(com.hubspot.hbase.filter.example.ExampleProtos.ChildProto value) {
        if (childProtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          childProto_ = value;
          onChanged();
        } else {
          childProtoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder setChildProto(
          com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.Builder builderForValue) {
        if (childProtoBuilder_ == null) {
          childProto_ = builderForValue.build();
          onChanged();
        } else {
          childProtoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder mergeChildProto(com.hubspot.hbase.filter.example.ExampleProtos.ChildProto value) {
        if (childProtoBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100) &&
              childProto_ != com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.getDefaultInstance()) {
            childProto_ =
              com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.newBuilder(childProto_).mergeFrom(value).buildPartial();
          } else {
            childProto_ = value;
          }
          onChanged();
        } else {
          childProtoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder clearChildProto() {
        if (childProtoBuilder_ == null) {
          childProto_ = com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.getDefaultInstance();
          onChanged();
        } else {
          childProtoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      public com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.Builder getChildProtoBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getChildProtoFieldBuilder().getBuilder();
      }
      public com.hubspot.hbase.filter.example.ExampleProtos.ChildProtoOrBuilder getChildProtoOrBuilder() {
        if (childProtoBuilder_ != null) {
          return childProtoBuilder_.getMessageOrBuilder();
        } else {
          return childProto_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.hubspot.hbase.filter.example.ExampleProtos.ChildProto, com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.Builder, com.hubspot.hbase.filter.example.ExampleProtos.ChildProtoOrBuilder> 
          getChildProtoFieldBuilder() {
        if (childProtoBuilder_ == null) {
          childProtoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.hubspot.hbase.filter.example.ExampleProtos.ChildProto, com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.Builder, com.hubspot.hbase.filter.example.ExampleProtos.ChildProtoOrBuilder>(
                  childProto_,
                  getParentForChildren(),
                  isClean());
          childProto_ = null;
        }
        return childProtoBuilder_;
      }
      
      // optional .com.hubspot.hbase.filter.example.ExampleProto.TestEnum test_enum = 10;
      private com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.TestEnum testEnum_ = com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.TestEnum.APPLE;
      public boolean hasTestEnum() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.TestEnum getTestEnum() {
        return testEnum_;
      }
      public Builder setTestEnum(com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.TestEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000200;
        testEnum_ = value;
        onChanged();
        return this;
      }
      public Builder clearTestEnum() {
        bitField0_ = (bitField0_ & ~0x00000200);
        testEnum_ = com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.TestEnum.APPLE;
        onChanged();
        return this;
      }
      
      // optional double double_test = 11;
      private double doubleTest_ ;
      public boolean hasDoubleTest() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public double getDoubleTest() {
        return doubleTest_;
      }
      public Builder setDoubleTest(double value) {
        bitField0_ |= 0x00000400;
        doubleTest_ = value;
        onChanged();
        return this;
      }
      public Builder clearDoubleTest() {
        bitField0_ = (bitField0_ & ~0x00000400);
        doubleTest_ = 0D;
        onChanged();
        return this;
      }
      
      // optional int32 default_test = 12 [default = 5];
      private int defaultTest_ = 5;
      public boolean hasDefaultTest() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public int getDefaultTest() {
        return defaultTest_;
      }
      public Builder setDefaultTest(int value) {
        bitField0_ |= 0x00000800;
        defaultTest_ = value;
        onChanged();
        return this;
      }
      public Builder clearDefaultTest() {
        bitField0_ = (bitField0_ & ~0x00000800);
        defaultTest_ = 5;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.hubspot.hbase.filter.example.ExampleProto)
    }
    
    static {
      defaultInstance = new ExampleProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.hubspot.hbase.filter.example.ExampleProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hubspot_hbase_filter_example_ChildProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hubspot_hbase_filter_example_ChildProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hubspot_hbase_filter_example_ExampleProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hubspot_hbase_filter_example_ExampleProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hubspot_hbase_filter_example_ExampleProto_InnerProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hubspot_hbase_filter_example_ExampleProto_InnerProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\022 com.hubspot.hbase.filte" +
      "r.example\"%\n\nChildProto\022\027\n\017child_proto_v" +
      "al\030\001 \001(\005\"\237\003\n\014ExampleProto\022\n\n\002id\030\001 \001(\003\022\021\n" +
      "\tportal_id\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\021\n\tbool_t" +
      "est\030\004 \001(\010\022\022\n\nfloat_test\030\005 \001(\002\022\022\n\nbytes_t" +
      "est\030\006 \001(\014\022\025\n\rrequired_test\030\007 \002(\005\022\024\n\014arra" +
      "y_values\030\010 \003(\t\022A\n\013child_proto\030\t \001(\0132,.co" +
      "m.hubspot.hbase.filter.example.ChildProt" +
      "o\022J\n\ttest_enum\030\n \001(\01627.com.hubspot.hbase" +
      ".filter.example.ExampleProto.TestEnum\022\023\n",
      "\013double_test\030\013 \001(\001\022\027\n\014default_test\030\014 \001(\005" +
      ":\0015\032\032\n\nInnerProto\022\014\n\004name\030\001 \001(\t\"!\n\010TestE" +
      "num\022\t\n\005APPLE\020\001\022\n\n\006ORANGE\020\002B\017B\rExamplePro" +
      "tos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_hubspot_hbase_filter_example_ChildProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_hubspot_hbase_filter_example_ChildProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hubspot_hbase_filter_example_ChildProto_descriptor,
              new java.lang.String[] { "ChildProtoVal", },
              com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.class,
              com.hubspot.hbase.filter.example.ExampleProtos.ChildProto.Builder.class);
          internal_static_com_hubspot_hbase_filter_example_ExampleProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_hubspot_hbase_filter_example_ExampleProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hubspot_hbase_filter_example_ExampleProto_descriptor,
              new java.lang.String[] { "Id", "PortalId", "Name", "BoolTest", "FloatTest", "BytesTest", "RequiredTest", "ArrayValues", "ChildProto", "TestEnum", "DoubleTest", "DefaultTest", },
              com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.class,
              com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.Builder.class);
          internal_static_com_hubspot_hbase_filter_example_ExampleProto_InnerProto_descriptor =
            internal_static_com_hubspot_hbase_filter_example_ExampleProto_descriptor.getNestedTypes().get(0);
          internal_static_com_hubspot_hbase_filter_example_ExampleProto_InnerProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hubspot_hbase_filter_example_ExampleProto_InnerProto_descriptor,
              new java.lang.String[] { "Name", },
              com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto.class,
              com.hubspot.hbase.filter.example.ExampleProtos.ExampleProto.InnerProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
