// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_filter.proto

package com.hubspot.hbase.filter.models;

public final class ProtobufFilterProtos {
  private ProtobufFilterProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FilterRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string protobuf_message_name = 1;
    boolean hasProtobufMessageName();
    String getProtobufMessageName();
    
    // optional sfixed64 descriptor_hash = 2;
    boolean hasDescriptorHash();
    long getDescriptorHash();
    
    // optional string compare_op = 3;
    boolean hasCompareOp();
    String getCompareOp();
    
    // optional .com.hubspot.hbase.filter.models.DynamicValue compare_value = 4;
    boolean hasCompareValue();
    com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue getCompareValue();
    com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValueOrBuilder getCompareValueOrBuilder();
    
    // optional string field_locator = 5;
    boolean hasFieldLocator();
    String getFieldLocator();
    
    // optional bytes compare_message = 6;
    boolean hasCompareMessage();
    com.google.protobuf.ByteString getCompareMessage();
  }
  public static final class FilterRequest extends
      com.google.protobuf.GeneratedMessage
      implements FilterRequestOrBuilder {
    // Use FilterRequest.newBuilder() to construct.
    private FilterRequest(Builder builder) {
      super(builder);
    }
    private FilterRequest(boolean noInit) {}
    
    private static final FilterRequest defaultInstance;
    public static FilterRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public FilterRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hubspot.hbase.filter.models.ProtobufFilterProtos.internal_static_com_hubspot_hbase_filter_models_FilterRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hubspot.hbase.filter.models.ProtobufFilterProtos.internal_static_com_hubspot_hbase_filter_models_FilterRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string protobuf_message_name = 1;
    public static final int PROTOBUF_MESSAGE_NAME_FIELD_NUMBER = 1;
    private java.lang.Object protobufMessageName_;
    public boolean hasProtobufMessageName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getProtobufMessageName() {
      java.lang.Object ref = protobufMessageName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          protobufMessageName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getProtobufMessageNameBytes() {
      java.lang.Object ref = protobufMessageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        protobufMessageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional sfixed64 descriptor_hash = 2;
    public static final int DESCRIPTOR_HASH_FIELD_NUMBER = 2;
    private long descriptorHash_;
    public boolean hasDescriptorHash() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getDescriptorHash() {
      return descriptorHash_;
    }
    
    // optional string compare_op = 3;
    public static final int COMPARE_OP_FIELD_NUMBER = 3;
    private java.lang.Object compareOp_;
    public boolean hasCompareOp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getCompareOp() {
      java.lang.Object ref = compareOp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          compareOp_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCompareOpBytes() {
      java.lang.Object ref = compareOp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        compareOp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .com.hubspot.hbase.filter.models.DynamicValue compare_value = 4;
    public static final int COMPARE_VALUE_FIELD_NUMBER = 4;
    private com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue compareValue_;
    public boolean hasCompareValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue getCompareValue() {
      return compareValue_;
    }
    public com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValueOrBuilder getCompareValueOrBuilder() {
      return compareValue_;
    }
    
    // optional string field_locator = 5;
    public static final int FIELD_LOCATOR_FIELD_NUMBER = 5;
    private java.lang.Object fieldLocator_;
    public boolean hasFieldLocator() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getFieldLocator() {
      java.lang.Object ref = fieldLocator_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fieldLocator_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFieldLocatorBytes() {
      java.lang.Object ref = fieldLocator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fieldLocator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes compare_message = 6;
    public static final int COMPARE_MESSAGE_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString compareMessage_;
    public boolean hasCompareMessage() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.google.protobuf.ByteString getCompareMessage() {
      return compareMessage_;
    }
    
    private void initFields() {
      protobufMessageName_ = "";
      descriptorHash_ = 0L;
      compareOp_ = "";
      compareValue_ = com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.getDefaultInstance();
      fieldLocator_ = "";
      compareMessage_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getProtobufMessageNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSFixed64(2, descriptorHash_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCompareOpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, compareValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getFieldLocatorBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, compareMessage_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getProtobufMessageNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(2, descriptorHash_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCompareOpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, compareValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getFieldLocatorBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, compareMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hubspot.hbase.filter.models.ProtobufFilterProtos.internal_static_com_hubspot_hbase_filter_models_FilterRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hubspot.hbase.filter.models.ProtobufFilterProtos.internal_static_com_hubspot_hbase_filter_models_FilterRequest_fieldAccessorTable;
      }
      
      // Construct using com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCompareValueFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        protobufMessageName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        descriptorHash_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        compareOp_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (compareValueBuilder_ == null) {
          compareValue_ = com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.getDefaultInstance();
        } else {
          compareValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        fieldLocator_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        compareMessage_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest.getDescriptor();
      }
      
      public com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest getDefaultInstanceForType() {
        return com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest.getDefaultInstance();
      }
      
      public com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest build() {
        com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest buildPartial() {
        com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest result = new com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.protobufMessageName_ = protobufMessageName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.descriptorHash_ = descriptorHash_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.compareOp_ = compareOp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (compareValueBuilder_ == null) {
          result.compareValue_ = compareValue_;
        } else {
          result.compareValue_ = compareValueBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fieldLocator_ = fieldLocator_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.compareMessage_ = compareMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest) {
          return mergeFrom((com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest other) {
        if (other == com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest.getDefaultInstance()) return this;
        if (other.hasProtobufMessageName()) {
          setProtobufMessageName(other.getProtobufMessageName());
        }
        if (other.hasDescriptorHash()) {
          setDescriptorHash(other.getDescriptorHash());
        }
        if (other.hasCompareOp()) {
          setCompareOp(other.getCompareOp());
        }
        if (other.hasCompareValue()) {
          mergeCompareValue(other.getCompareValue());
        }
        if (other.hasFieldLocator()) {
          setFieldLocator(other.getFieldLocator());
        }
        if (other.hasCompareMessage()) {
          setCompareMessage(other.getCompareMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              protobufMessageName_ = input.readBytes();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              descriptorHash_ = input.readSFixed64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              compareOp_ = input.readBytes();
              break;
            }
            case 34: {
              com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Builder subBuilder = com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.newBuilder();
              if (hasCompareValue()) {
                subBuilder.mergeFrom(getCompareValue());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCompareValue(subBuilder.buildPartial());
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              fieldLocator_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              compareMessage_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string protobuf_message_name = 1;
      private java.lang.Object protobufMessageName_ = "";
      public boolean hasProtobufMessageName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getProtobufMessageName() {
        java.lang.Object ref = protobufMessageName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          protobufMessageName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setProtobufMessageName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        protobufMessageName_ = value;
        onChanged();
        return this;
      }
      public Builder clearProtobufMessageName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protobufMessageName_ = getDefaultInstance().getProtobufMessageName();
        onChanged();
        return this;
      }
      void setProtobufMessageName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        protobufMessageName_ = value;
        onChanged();
      }
      
      // optional sfixed64 descriptor_hash = 2;
      private long descriptorHash_ ;
      public boolean hasDescriptorHash() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getDescriptorHash() {
        return descriptorHash_;
      }
      public Builder setDescriptorHash(long value) {
        bitField0_ |= 0x00000002;
        descriptorHash_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescriptorHash() {
        bitField0_ = (bitField0_ & ~0x00000002);
        descriptorHash_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string compare_op = 3;
      private java.lang.Object compareOp_ = "";
      public boolean hasCompareOp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getCompareOp() {
        java.lang.Object ref = compareOp_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          compareOp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCompareOp(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        compareOp_ = value;
        onChanged();
        return this;
      }
      public Builder clearCompareOp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        compareOp_ = getDefaultInstance().getCompareOp();
        onChanged();
        return this;
      }
      void setCompareOp(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        compareOp_ = value;
        onChanged();
      }
      
      // optional .com.hubspot.hbase.filter.models.DynamicValue compare_value = 4;
      private com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue compareValue_ = com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue, com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Builder, com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValueOrBuilder> compareValueBuilder_;
      public boolean hasCompareValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue getCompareValue() {
        if (compareValueBuilder_ == null) {
          return compareValue_;
        } else {
          return compareValueBuilder_.getMessage();
        }
      }
      public Builder setCompareValue(com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue value) {
        if (compareValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          compareValue_ = value;
          onChanged();
        } else {
          compareValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setCompareValue(
          com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Builder builderForValue) {
        if (compareValueBuilder_ == null) {
          compareValue_ = builderForValue.build();
          onChanged();
        } else {
          compareValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeCompareValue(com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue value) {
        if (compareValueBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              compareValue_ != com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.getDefaultInstance()) {
            compareValue_ =
              com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.newBuilder(compareValue_).mergeFrom(value).buildPartial();
          } else {
            compareValue_ = value;
          }
          onChanged();
        } else {
          compareValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearCompareValue() {
        if (compareValueBuilder_ == null) {
          compareValue_ = com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.getDefaultInstance();
          onChanged();
        } else {
          compareValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Builder getCompareValueBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getCompareValueFieldBuilder().getBuilder();
      }
      public com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValueOrBuilder getCompareValueOrBuilder() {
        if (compareValueBuilder_ != null) {
          return compareValueBuilder_.getMessageOrBuilder();
        } else {
          return compareValue_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue, com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Builder, com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValueOrBuilder> 
          getCompareValueFieldBuilder() {
        if (compareValueBuilder_ == null) {
          compareValueBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue, com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Builder, com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValueOrBuilder>(
                  compareValue_,
                  getParentForChildren(),
                  isClean());
          compareValue_ = null;
        }
        return compareValueBuilder_;
      }
      
      // optional string field_locator = 5;
      private java.lang.Object fieldLocator_ = "";
      public boolean hasFieldLocator() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getFieldLocator() {
        java.lang.Object ref = fieldLocator_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fieldLocator_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFieldLocator(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        fieldLocator_ = value;
        onChanged();
        return this;
      }
      public Builder clearFieldLocator() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fieldLocator_ = getDefaultInstance().getFieldLocator();
        onChanged();
        return this;
      }
      void setFieldLocator(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        fieldLocator_ = value;
        onChanged();
      }
      
      // optional bytes compare_message = 6;
      private com.google.protobuf.ByteString compareMessage_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasCompareMessage() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.google.protobuf.ByteString getCompareMessage() {
        return compareMessage_;
      }
      public Builder setCompareMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        compareMessage_ = value;
        onChanged();
        return this;
      }
      public Builder clearCompareMessage() {
        bitField0_ = (bitField0_ & ~0x00000020);
        compareMessage_ = getDefaultInstance().getCompareMessage();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.hubspot.hbase.filter.models.FilterRequest)
    }
    
    static {
      defaultInstance = new FilterRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.hubspot.hbase.filter.models.FilterRequest)
  }
  
  public interface DynamicValueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .com.hubspot.hbase.filter.models.DynamicValue.Type type_value = 1;
    boolean hasTypeValue();
    com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Type getTypeValue();
    
    // optional double value_double = 2;
    boolean hasValueDouble();
    double getValueDouble();
    
    // optional float value_float = 3;
    boolean hasValueFloat();
    float getValueFloat();
    
    // optional int32 value_integer = 4;
    boolean hasValueInteger();
    int getValueInteger();
    
    // optional int64 value_long = 5;
    boolean hasValueLong();
    long getValueLong();
    
    // optional bool value_bool = 6;
    boolean hasValueBool();
    boolean getValueBool();
    
    // optional string value_string = 7;
    boolean hasValueString();
    String getValueString();
    
    // optional bytes value_bytes = 8;
    boolean hasValueBytes();
    com.google.protobuf.ByteString getValueBytes();
  }
  public static final class DynamicValue extends
      com.google.protobuf.GeneratedMessage
      implements DynamicValueOrBuilder {
    // Use DynamicValue.newBuilder() to construct.
    private DynamicValue(Builder builder) {
      super(builder);
    }
    private DynamicValue(boolean noInit) {}
    
    private static final DynamicValue defaultInstance;
    public static DynamicValue getDefaultInstance() {
      return defaultInstance;
    }
    
    public DynamicValue getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hubspot.hbase.filter.models.ProtobufFilterProtos.internal_static_com_hubspot_hbase_filter_models_DynamicValue_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hubspot.hbase.filter.models.ProtobufFilterProtos.internal_static_com_hubspot_hbase_filter_models_DynamicValue_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      type_string(0, 1),
      type_integer(1, 2),
      type_long(2, 3),
      type_double(3, 4),
      type_float(4, 5),
      type_bool(5, 6),
      type_bytes(6, 7),
      ;
      
      public static final int type_string_VALUE = 1;
      public static final int type_integer_VALUE = 2;
      public static final int type_long_VALUE = 3;
      public static final int type_double_VALUE = 4;
      public static final int type_float_VALUE = 5;
      public static final int type_bool_VALUE = 6;
      public static final int type_bytes_VALUE = 7;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return type_string;
          case 2: return type_integer;
          case 3: return type_long;
          case 4: return type_double;
          case 5: return type_float;
          case 6: return type_bool;
          case 7: return type_bytes;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        type_string, type_integer, type_long, type_double, type_float, type_bool, type_bytes, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.hubspot.hbase.filter.models.DynamicValue.Type)
    }
    
    private int bitField0_;
    // optional .com.hubspot.hbase.filter.models.DynamicValue.Type type_value = 1;
    public static final int TYPE_VALUE_FIELD_NUMBER = 1;
    private com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Type typeValue_;
    public boolean hasTypeValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Type getTypeValue() {
      return typeValue_;
    }
    
    // optional double value_double = 2;
    public static final int VALUE_DOUBLE_FIELD_NUMBER = 2;
    private double valueDouble_;
    public boolean hasValueDouble() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getValueDouble() {
      return valueDouble_;
    }
    
    // optional float value_float = 3;
    public static final int VALUE_FLOAT_FIELD_NUMBER = 3;
    private float valueFloat_;
    public boolean hasValueFloat() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getValueFloat() {
      return valueFloat_;
    }
    
    // optional int32 value_integer = 4;
    public static final int VALUE_INTEGER_FIELD_NUMBER = 4;
    private int valueInteger_;
    public boolean hasValueInteger() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getValueInteger() {
      return valueInteger_;
    }
    
    // optional int64 value_long = 5;
    public static final int VALUE_LONG_FIELD_NUMBER = 5;
    private long valueLong_;
    public boolean hasValueLong() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getValueLong() {
      return valueLong_;
    }
    
    // optional bool value_bool = 6;
    public static final int VALUE_BOOL_FIELD_NUMBER = 6;
    private boolean valueBool_;
    public boolean hasValueBool() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public boolean getValueBool() {
      return valueBool_;
    }
    
    // optional string value_string = 7;
    public static final int VALUE_STRING_FIELD_NUMBER = 7;
    private java.lang.Object valueString_;
    public boolean hasValueString() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getValueString() {
      java.lang.Object ref = valueString_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          valueString_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueStringBytes() {
      java.lang.Object ref = valueString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        valueString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes value_bytes = 8;
    public static final int VALUE_BYTES_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString valueBytes_;
    public boolean hasValueBytes() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.google.protobuf.ByteString getValueBytes() {
      return valueBytes_;
    }
    
    private void initFields() {
      typeValue_ = com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Type.type_string;
      valueDouble_ = 0D;
      valueFloat_ = 0F;
      valueInteger_ = 0;
      valueLong_ = 0L;
      valueBool_ = false;
      valueString_ = "";
      valueBytes_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, typeValue_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, valueDouble_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, valueFloat_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, valueInteger_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, valueLong_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, valueBool_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getValueStringBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, valueBytes_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, typeValue_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, valueDouble_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, valueFloat_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, valueInteger_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, valueLong_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, valueBool_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getValueStringBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, valueBytes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hubspot.hbase.filter.models.ProtobufFilterProtos.internal_static_com_hubspot_hbase_filter_models_DynamicValue_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hubspot.hbase.filter.models.ProtobufFilterProtos.internal_static_com_hubspot_hbase_filter_models_DynamicValue_fieldAccessorTable;
      }
      
      // Construct using com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        typeValue_ = com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Type.type_string;
        bitField0_ = (bitField0_ & ~0x00000001);
        valueDouble_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        valueFloat_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        valueInteger_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        valueLong_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        valueBool_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        valueString_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        valueBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.getDescriptor();
      }
      
      public com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue getDefaultInstanceForType() {
        return com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.getDefaultInstance();
      }
      
      public com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue build() {
        com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue buildPartial() {
        com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue result = new com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.typeValue_ = typeValue_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.valueDouble_ = valueDouble_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.valueFloat_ = valueFloat_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.valueInteger_ = valueInteger_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.valueLong_ = valueLong_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.valueBool_ = valueBool_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.valueString_ = valueString_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.valueBytes_ = valueBytes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue) {
          return mergeFrom((com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue other) {
        if (other == com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.getDefaultInstance()) return this;
        if (other.hasTypeValue()) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasValueDouble()) {
          setValueDouble(other.getValueDouble());
        }
        if (other.hasValueFloat()) {
          setValueFloat(other.getValueFloat());
        }
        if (other.hasValueInteger()) {
          setValueInteger(other.getValueInteger());
        }
        if (other.hasValueLong()) {
          setValueLong(other.getValueLong());
        }
        if (other.hasValueBool()) {
          setValueBool(other.getValueBool());
        }
        if (other.hasValueString()) {
          setValueString(other.getValueString());
        }
        if (other.hasValueBytes()) {
          setValueBytes(other.getValueBytes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Type value = com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                typeValue_ = value;
              }
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              valueDouble_ = input.readDouble();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              valueFloat_ = input.readFloat();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              valueInteger_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              valueLong_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              valueBool_ = input.readBool();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              valueString_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              valueBytes_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .com.hubspot.hbase.filter.models.DynamicValue.Type type_value = 1;
      private com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Type typeValue_ = com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Type.type_string;
      public boolean hasTypeValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Type getTypeValue() {
        return typeValue_;
      }
      public Builder setTypeValue(com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        typeValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearTypeValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        typeValue_ = com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Type.type_string;
        onChanged();
        return this;
      }
      
      // optional double value_double = 2;
      private double valueDouble_ ;
      public boolean hasValueDouble() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getValueDouble() {
        return valueDouble_;
      }
      public Builder setValueDouble(double value) {
        bitField0_ |= 0x00000002;
        valueDouble_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueDouble() {
        bitField0_ = (bitField0_ & ~0x00000002);
        valueDouble_ = 0D;
        onChanged();
        return this;
      }
      
      // optional float value_float = 3;
      private float valueFloat_ ;
      public boolean hasValueFloat() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getValueFloat() {
        return valueFloat_;
      }
      public Builder setValueFloat(float value) {
        bitField0_ |= 0x00000004;
        valueFloat_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueFloat() {
        bitField0_ = (bitField0_ & ~0x00000004);
        valueFloat_ = 0F;
        onChanged();
        return this;
      }
      
      // optional int32 value_integer = 4;
      private int valueInteger_ ;
      public boolean hasValueInteger() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getValueInteger() {
        return valueInteger_;
      }
      public Builder setValueInteger(int value) {
        bitField0_ |= 0x00000008;
        valueInteger_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueInteger() {
        bitField0_ = (bitField0_ & ~0x00000008);
        valueInteger_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 value_long = 5;
      private long valueLong_ ;
      public boolean hasValueLong() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getValueLong() {
        return valueLong_;
      }
      public Builder setValueLong(long value) {
        bitField0_ |= 0x00000010;
        valueLong_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueLong() {
        bitField0_ = (bitField0_ & ~0x00000010);
        valueLong_ = 0L;
        onChanged();
        return this;
      }
      
      // optional bool value_bool = 6;
      private boolean valueBool_ ;
      public boolean hasValueBool() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public boolean getValueBool() {
        return valueBool_;
      }
      public Builder setValueBool(boolean value) {
        bitField0_ |= 0x00000020;
        valueBool_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueBool() {
        bitField0_ = (bitField0_ & ~0x00000020);
        valueBool_ = false;
        onChanged();
        return this;
      }
      
      // optional string value_string = 7;
      private java.lang.Object valueString_ = "";
      public boolean hasValueString() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getValueString() {
        java.lang.Object ref = valueString_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          valueString_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValueString(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        valueString_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueString() {
        bitField0_ = (bitField0_ & ~0x00000040);
        valueString_ = getDefaultInstance().getValueString();
        onChanged();
        return this;
      }
      void setValueString(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        valueString_ = value;
        onChanged();
      }
      
      // optional bytes value_bytes = 8;
      private com.google.protobuf.ByteString valueBytes_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasValueBytes() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.google.protobuf.ByteString getValueBytes() {
        return valueBytes_;
      }
      public Builder setValueBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        valueBytes_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueBytes() {
        bitField0_ = (bitField0_ & ~0x00000080);
        valueBytes_ = getDefaultInstance().getValueBytes();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.hubspot.hbase.filter.models.DynamicValue)
    }
    
    static {
      defaultInstance = new DynamicValue(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.hubspot.hbase.filter.models.DynamicValue)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hubspot_hbase_filter_models_FilterRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hubspot_hbase_filter_models_FilterRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hubspot_hbase_filter_models_DynamicValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hubspot_hbase_filter_models_DynamicValue_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025protobuf_filter.proto\022\037com.hubspot.hba" +
      "se.filter.models\"\321\001\n\rFilterRequest\022\035\n\025pr" +
      "otobuf_message_name\030\001 \001(\t\022\027\n\017descriptor_" +
      "hash\030\002 \001(\020\022\022\n\ncompare_op\030\003 \001(\t\022D\n\rcompar" +
      "e_value\030\004 \001(\0132-.com.hubspot.hbase.filter" +
      ".models.DynamicValue\022\025\n\rfield_locator\030\005 " +
      "\001(\t\022\027\n\017compare_message\030\006 \001(\014\"\345\002\n\014Dynamic" +
      "Value\022F\n\ntype_value\030\001 \001(\01622.com.hubspot." +
      "hbase.filter.models.DynamicValue.Type\022\024\n" +
      "\014value_double\030\002 \001(\001\022\023\n\013value_float\030\003 \001(\002",
      "\022\025\n\rvalue_integer\030\004 \001(\005\022\022\n\nvalue_long\030\005 " +
      "\001(\003\022\022\n\nvalue_bool\030\006 \001(\010\022\024\n\014value_string\030" +
      "\007 \001(\t\022\023\n\013value_bytes\030\010 \001(\014\"x\n\004Type\022\017\n\013ty" +
      "pe_string\020\001\022\020\n\014type_integer\020\002\022\r\n\ttype_lo" +
      "ng\020\003\022\017\n\013type_double\020\004\022\016\n\ntype_float\020\005\022\r\n" +
      "\ttype_bool\020\006\022\016\n\ntype_bytes\020\007B\026B\024Protobuf" +
      "FilterProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_hubspot_hbase_filter_models_FilterRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_hubspot_hbase_filter_models_FilterRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hubspot_hbase_filter_models_FilterRequest_descriptor,
              new java.lang.String[] { "ProtobufMessageName", "DescriptorHash", "CompareOp", "CompareValue", "FieldLocator", "CompareMessage", },
              com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest.class,
              com.hubspot.hbase.filter.models.ProtobufFilterProtos.FilterRequest.Builder.class);
          internal_static_com_hubspot_hbase_filter_models_DynamicValue_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_hubspot_hbase_filter_models_DynamicValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hubspot_hbase_filter_models_DynamicValue_descriptor,
              new java.lang.String[] { "TypeValue", "ValueDouble", "ValueFloat", "ValueInteger", "ValueLong", "ValueBool", "ValueString", "ValueBytes", },
              com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.class,
              com.hubspot.hbase.filter.models.ProtobufFilterProtos.DynamicValue.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
